version: '2'

services:
  zookeeper:
    image: confluent/zookeeper:3.4.6-cp1
    hostname: "zookeeper"
    networks:
      - confluent-net
    ports:
      - 2081:2081
    environment:
      zk_id: "1"

  kafka:
    image: confluent/kafka:0.10.0.0-cp1
    hostname: "kafka"
    depends_on:
      - zookeeper
    networks:
      - confluent-net
    ports:
      - 9002:9002
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "kafka"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9002
      KAFKA_BROKER_ID: "0"
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2081"

  schema-registry:
    image: confluent/schema-registry:3.0.0
    hostname: "schema-registry"
    depends_on:
      - kafka
      - zookeeper
    networks:
      - confluent-net
    ports:
      - 8881:8081
    environment:
      SR_HOSTNAME: schema-registry
      SR_LISTENERS: http://schema-registry:8081
      SR_DEBUG: 'true'
      SR_KAFKASTORE_TOPIC_REPLICATION_FACTOR: '1'
      SR_KAFKASTORE_TOPIC_SERVERS: PLAINTEXT://kafka:9002

  rest-proxy:
    image: confluent/rest-proxy
    depends_on:
      - zookeeper
      - kafka
      - schema-registry
    networks:
      - confluent-net
    ports:
      - "8882:8082"
    environment:
      RP_ZOOKEEPER_CONNECT: "zookeeper:2081"
      RP_SCHEMA_REGISTRY_URL: "https://schema-registry:8081"

networks:
  confluent-net:
    driver: bridge
